package rockstar.client.network;


import rockstar.client.*;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import lombok.Generated;

public final class HttpStatus {
    public static final int internalField0227 = 100;
    public static final int internalField0228 = 101;
    public static final int internalField1053 = 102;
    public static final int internalField1055 = 103;
    public static final int internalField1056 = 200;
    public static final int internalField1054 = 201;
    public static final int internalField1464 = 202;
    public static final int internalField1470 = 203;
    public static final int internalField1465 = 204;
    public static final int internalField1463 = 205;
    public static final int internalField1466 = 206;
    public static final int internalField1467 = 207;
    public static final int internalField1469 = 208;
    public static final int internalField1468 = 226;
    public static final int internalField1740 = 300;
    public static final int internalField1741 = 301;
    public static final int internalField1736 = 302;
    public static final int internalField1735 = 303;
    public static final int internalField1748 = 304;
    public static final int internalField1733 = 305;
    public static final int internalField1738 = 306;
    public static final int internalField1739 = 307;
    public static final int internalField1742 = 308;
    public static final int internalField1743 = 400;
    public static final int internalField1744 = 401;
    public static final int internalField1745 = 402;
    public static final int internalField1746 = 403;
    public static final int internalField1747 = 404;
    public static final int internalField1734 = 405;
    public static final int internalField1737 = 406;
    public static final int internalField1860 = 407;
    public static final int internalField1861 = 408;
    public static final int internalField1862 = 409;
    public static final int internalField1863 = 410;
    public static final int internalField1864 = 411;
    public static final int internalField1865 = 412;
    public static final int internalField1867 = 413;
    public static final int internalField1866 = 414;
    public static final int internalField1868 = 415;
    public static final int internalField1871 = 416;
    public static final int internalField1870 = 417;
    public static final int internalField1891 = 418;
    public static final int internalField1890 = 421;
    public static final int internalField1889 = 422;
    public static final int internalField1888 = 423;
    public static final int internalField1887 = 424;
    public static final int internalField1886 = 425;
    public static final int internalField1885 = 426;
    public static final int internalField1884 = 428;
    public static final int internalField1883 = 429;
    public static final int internalField1882 = 431;
    public static final int internalField1869 = 451;
    public static final int internalField1880 = 500;
    public static final int internalField1879 = 501;
    public static final int internalField1878 = 502;
    public static final int internalField1877 = 503;
    public static final int internalField1876 = 504;
    public static final int internalField1875 = 505;
    public static final int internalField1881 = 506;
    public static final int internalField1874 = 507;
    public static final int internalField1873 = 508;
    public static final int internalField1872 = 510;
    public static final int internalField1928 = 511;
    public static final Map<Integer, String> internalField0543;

    @Generated
    private HttpStatus() {
        throw new UnsupportedOperationException("This is a utility class and cannot be instantiated");
    }

    static {
        HashMap<Integer, String> hashMap = new HashMap<Integer, String>();
        hashMap.put(100, "Continue");
        hashMap.put(101, "Switching Protocols");
        hashMap.put(102, "Processing");
        hashMap.put(103, "Early Hints");
        hashMap.put(200, "OK");
        hashMap.put(201, "Created");
        hashMap.put(202, "Accepted");
        hashMap.put(203, "Non-Authoritative Information");
        hashMap.put(204, "No Content");
        hashMap.put(205, "Reset Content");
        hashMap.put(206, "Partial Content");
        hashMap.put(207, "Multi-Status");
        hashMap.put(208, "Already Reported");
        hashMap.put(226, "IM Used");
        hashMap.put(300, "Multiple Choices");
        hashMap.put(301, "Moved Permanently");
        hashMap.put(302, "Moved Temporarily");
        hashMap.put(303, "See Other");
        hashMap.put(304, "Not Modified");
        hashMap.put(305, "Use Proxy");
        hashMap.put(306, "Unused");
        hashMap.put(307, "Temporary Redirect");
        hashMap.put(308, "Permanent Redirect");
        hashMap.put(400, "Bad Request");
        hashMap.put(401, "Unauthorized");
        hashMap.put(402, "Payment Required");
        hashMap.put(403, "Forbidden");
        hashMap.put(404, "Not Found");
        hashMap.put(405, "Method Not Allowed");
        hashMap.put(406, "Not Acceptable");
        hashMap.put(407, "Proxy Authentication Required");
        hashMap.put(408, "Request Timeout");
        hashMap.put(409, "Conflict");
        hashMap.put(410, "Gone");
        hashMap.put(411, "Length Required");
        hashMap.put(412, "Precondition Failed");
        hashMap.put(413, "Payload Too Large");
        hashMap.put(414, "URI Too Long");
        hashMap.put(415, "Unsupported Media Type");
        hashMap.put(416, "Range Not Satisfiable");
        hashMap.put(417, "Expectation Failed");
        hashMap.put(418, "I'm a teapot");
        hashMap.put(421, "Misdirected Request");
        hashMap.put(422, "Unprocessable Content");
        hashMap.put(423, "Locked");
        hashMap.put(424, "Failed Dependency");
        hashMap.put(425, "Too Early");
        hashMap.put(426, "Upgrade Required");
        hashMap.put(428, "Precondition Required");
        hashMap.put(429, "Too Many Requests");
        hashMap.put(431, "Request Header Fields Too Large");
        hashMap.put(451, "Unavailable For Legal Reasons");
        hashMap.put(500, "Internal Server Error");
        hashMap.put(501, "Not Implemented");
        hashMap.put(502, "Bad Gateway");
        hashMap.put(503, "Service Unavailable");
        hashMap.put(504, "Gateway Timeout");
        hashMap.put(505, "HTTP Version Not Supported");
        hashMap.put(506, "Variant Also Negotiates");
        hashMap.put(507, "Insufficient Storage");
        hashMap.put(508, "Loop Detected");
        hashMap.put(510, "Not Extended");
        hashMap.put(511, "Network Authentication Required");
        internalField0543 = Collections.unmodifiableMap(hashMap);
    }
}

